#!/bin/bash

##
# Script to delete remote git branches
##

# Fetch the remote resources
git fetch

# Loop through all remote merged branches
#for branch in $(git branch -r --merged | grep -v HEAD | grep -v develop | grep -v main | grep -v main | sed /\*/d); do
for branch in $(git branch -r | grep -v HEAD | grep -v *dev | grep -v main | grep -v main | sed /\*/d); do
        if [ -z "$(git log -1 --since='Feb 15, 2024' -s ${branch})" ]; then
                echo -e `git show --format="%ci|%cr|%an|" ${branch} | head -n 1` \\t$branch
                out=$(echo -e `git show --format="%ci|%cr|%an|" ${branch} | head -n 1` $branch)
                remote_branch=$(echo ${branch} | sed 's#origin/##' )
                echo $out >> branchname.csv
                # To delete the branches uncomment the bellow git delete command
                git push origin --delete ${remote_branch}
        fi
done
